### ISSUE TITLE
You gotta add me boii [Open to see more Info]

### ISSUE THREAD

**Issue by M-T3K** [matiasilva/caislcs#1]
The first issue is with the Readme:

- In the section of languages, it needs work. For this purpose, a "language of your choice" should be more specific. ( I'll make the correction once you add me as a contributor)

- Using IDEs and "things" like github -> Man that ain't gud.

- Projects from students: I don't think this is something good. As a matter of fact, I think people should spend time on their own repos on their own github, and add links to each person's repo on the readme (Much more organized and people will have free access to their stuff, and will also help us to monitor progress)

- I wouldn't use the word classes. I would use something like "sessions" because classes sound too much like school, I don't know if you get what im saying.

- The class info, I can update that stuff with a bunch of good information.

Also, I don't like the way you are introducing p5. I know you make a couple simple examples on the "syllabus" about native vs p5, but the truth is you aren't putting any "real life examples" per say, like you are not comparing, for instance, a fully native javascript 2D gravity simulator with one done in p5.js (Obviously p5 is shorter, but examples like that would help explain the "why").

Finally, I suggest we have an entire unit based on problem solving, similar to what we did at the beginning of the year, in which we give problems for people to solve, and solutions. However, the solutions would be implemented in different languages so that people can't just copy/paste. The thing about this unit is that it isn't a good unit to do at school (There's other, cooler stuff to do) so I think this problem solving Unit should be for the entire year, a couple problems a week. We should hangouts one of these days to discuss these. It would be particularly useful for IB Computer Science people, because we should have a lot of arrays and Data structure problems that are often used in the IB.

**Comment by matiasilva** [comment]
1. Languages need work, true. Even though most learn Java, I wanted to open it up to other people.
2. Valid point. Should've phrased it better, but the idea is still there.
3. Perhaps have them file a pull request when they are done with the project to add it to this? Whether they submit their own projects or unit challenges, they should all go in here as student work.
4. Got it completely.
5. OK
6. I simply didn't have time to elaborate on more examples. I've been writing some examples on CodePen that I will slowly start to add to the syllabus. The syllabus is still in development, it will only really be used next year.
7. That could be something we do at the end of each session. We will introduce the problem at the end, let them show the solution if they find it over the week, and review it next session.
